### ISSUE TITLE
en_US locale not detected

### ISSUE THREAD

**Issue by gardar** [uroni/urbackup_frontend_wx#2]
Upon launching urbackup_client_gui I receive this message:

> Cannot set locale to language "English".
> locale 'en_GB' cannot be set.

My system only had en_US enabled as a locale and it seems like the client is not detecting it.
It's not possible to go further at that point as the application just closes.

After I generated a en_GB locale and then the error disappeared.

I'd suggest en_US to be added or better yet, change the client so it doesn't relay on a pre defined list of "supported locales"

**Comment by uroni** [comment]
Should be fixed by now.
